- name: Run the embeded tasks
  hosts: localhost
  gather_facts: no

  vars:
    zyx: "habib"

  tasks:

    #send parameters into the task lists
    - include: embed-tasks.yaml xyz="abidin"

    #send parameters into the playbook 
- include: embed-playbook.yaml
  vars:
    xyz: "abidin"