- name: ansible variables
  hosts: localhost
  gather_facts: yes

  tasks:

    - name: access ansible variables
      debug: 
        msg: "{{ ansible_version }}"
        # msg: "{{ ansible_version.full }} "

    # gather_facts: yes 
    # for machine related things
    - name: access ansible variables - machine related
      debug: 
        msg: "{{ ansible_facts.hostname }}"

    - name: access hostname while gather_facts:no
      debug: 
        msg: "{{ inventory_hostname }}"

    # add ansible-playbook .... -i hosts 
    - name: access magic variables - from host file
      debug: 
        msg: "{% for host in groups['web'] %}
               {{ host }}
              {% endfor %}"
    
